//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Book
    {
        public int BookID { get; set; }

        [Required]
        [StringLength(150, ErrorMessage = "Must be between 2 to 75 characters", MinimumLength = 2)]
        public string BookName { get; set; }
        
        [Required]
        public System.DateTime BookReleaseDate { get; set; }

        public string StringDate { get { return BookReleaseDate.ToShortDateString();  } set { value = BookReleaseDate.ToShortDateString(); } } 

        [Required]
        public int BookPagesNumber { get; set; }

        [StringLength(75, ErrorMessage = "Maximum 75 characters")]
        public string SubCategory { get; set; }
        
        [Required]
        public float BookPrice { get; set; }
        
        [Required]
        public short BookCount { get; set; }
        
        [Required]
        public int CategoryID { get; set; }
        
        [Required]
        public int AuthorID { get; set; }
        
        [Required]
        public int PublisherID { get; set; }

        [Required]
        public int PlaceID { get; set; }

        public virtual Author Author { get; set; }

        public virtual Category Category { get; set; }

        public virtual Place Place { get; set; }

        public virtual Publisher Publisher { get; set; }
    }
}
